name = "MacroEnergySystemsScaling"
uuid = "e07ba8b4-499e-4f54-a885-af58260c741f"
authors = "Ruaridh Macdonald <rmacd@mit.edu>"
version = "0.0.3"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1"
JuMP = "1"
MathOptInterface = "1"
OrderedCollections = "1"
