name = "MacroEnergySystemsScaling"
authors = "Ruaridh Macdonald <rmacd@mit.edu>"
version = "0.0.1"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
